# Generated by Django 5.2.7 on 2025-10-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('cta_text', models.CharField(blank=True, default='Узнать больше', max_length=60, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(blank=True, default='#lead', max_length=255, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Фон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайд хиро',
                'verbose_name_plural': 'Слайды хиро',
                'ordering': ['order', 'id'],
            },
        ),
    ]
