# Generated by Django 5.2.7 on 2025-10-21 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Почему мы', max_length=120, verbose_name='Заголовок секции')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='usp/', verbose_name='Изображение слева')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секция преимуществ',
                'verbose_name_plural': 'Секции преимуществ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='USPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('ruler', 'Замер/дизайн'), ('truck', 'Доставка/монтаж'), ('shield', 'Гарантия'), ('timer', 'Сроки'), ('cube', 'Материалы'), ('star', 'Качество')], default='star', max_length=24, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.uspsection')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'id'],
            },
        ),
    ]
