# Generated by Django 5.2.7 on 2025-10-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_uspsection_uspitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать секцию')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(default='О компании', max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('years', models.PositiveIntegerField(default=10, verbose_name='Лет на рынке')),
                ('projects', models.PositiveIntegerField(default=1000, verbose_name='Проектов')),
                ('partners', models.PositiveIntegerField(default=100, verbose_name='Партнёров')),
                ('cta_text', models.CharField(default='Заказать проект', max_length=60, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(default='#lead', max_length=255, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Секция — О компании',
                'verbose_name_plural': 'Секция — О компании',
                'ordering': ['order', 'id'],
            },
        ),
    ]
