# Generated by Django 5.2.7 on 2025-10-21 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наша мебель в интерьере', max_length=160, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать секцию')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секция галереи',
                'verbose_name_plural': 'Секции галереи',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=180, verbose_name='ALT/подпись')),
                ('size', models.CharField(choices=[('auto', 'Обычная'), ('wide', 'Широкая'), ('tall', 'Высокая')], default='auto', max_length=8, verbose_name='Размер в сетке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.gallerysection')),
            ],
            options={
                'verbose_name': 'Картинка галереи',
                'verbose_name_plural': 'Картинки галереи',
                'ordering': ['order', 'id'],
            },
        ),
    ]
