# Generated by Django 5.2.7 on 2025-10-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_gallerysection_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать секцию')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(default='Отзывы клиентов', max_length=160, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фоновое изображение')),
                ('use_slider', models.BooleanField(default=True, verbose_name='Слайдер (Swiper)')),
            ],
            options={
                'verbose_name': 'Секция отзывов',
                'verbose_name_plural': 'Секция отзывов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Автор')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оценка')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/avatars/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.reviewsection')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
