# Generated by Django 5.2.7 on 2025-10-22 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_reviewsection_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX или 8XXXXXXXXXX', regex='^(?:\\+7|8)\\s*\\(?\\d{3}\\)?\\s*-?\\s*\\d{3}\\s*-?\\s*\\d{2}\\s*-?\\s*\\d{2}$')], verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('utm_source', models.CharField(blank=True, max_length=80, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=80, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='utm_campaign')),
                ('referer', models.URLField(blank=True, verbose_name='Реферер')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка менеджера')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать секцию')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(default='Мы спроектируем и изготовим, доставим бесплатно', max_length=160, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='cta/', verbose_name='Фон')),
                ('cta_text', models.CharField(default='Отправить', max_length=60, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Секция CTA/Форма',
                'verbose_name_plural': 'Секция CTA/Форма',
                'ordering': ['order', 'id'],
            },
        ),
    ]
