# Generated by Django 5.2.7 on 2025-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_lead_leadsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Источник'),
        ),
    ]
