# Generated by Django 5.2.7 on 2025-10-29 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_lead_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_photos/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Подпись')),
                ('size', models.CharField(choices=[('normal', 'Обычная'), ('wide', 'Широкая (2 колонки)'), ('tall', 'Высокая (2 строки)')], default='normal', max_length=12, verbose_name='Размер в сетке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фото категории',
                'verbose_name_plural': 'Фото категории',
                'ordering': ('order', 'id'),
            },
        ),
    ]
