# Generated by Django 5.2.7 on 2025-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_categoryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/headers/', verbose_name='Хедер: большое изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='header_subtitle',
            field=models.CharField(blank=True, max_length=240, verbose_name='Хедер: подзаголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='header_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Хедер: заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=240, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/', verbose_name='Картинка (превью)'),
        ),
    ]
