# Generated by Django 5.2.7 on 2025-10-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_category_description_category_header_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Фон хедера')),
                ('title', models.CharField(default='Контакты', max_length=160, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='Подзаголовок')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk', models.URLField(blank=True, verbose_name='VK')),
                ('schedule', models.TextField(blank=True, help_text='Каждую строку – отдельной строкой, например: Пн–Пт 10:00–20:00', verbose_name='График работы')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('map_embed', models.TextField(blank=True, help_text='Вставь iframe от Яндекс/Google. Если заполнено – координаты ниже игнорятся.', verbose_name='Карта (iframe-embed)')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('map_zoom', models.PositiveSmallIntegerField(default=15, verbose_name='Зум')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница «Контакты»',
                'verbose_name_plural': 'Страница «Контакты»',
            },
        ),
    ]
