# Generated by Django 5.2.7 on 2025-10-30 02:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Публичная оферта', max_length=160, verbose_name='Заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='legal/', verbose_name='Файл оферты (PDF/Docx)')),
                ('html', models.TextField(blank=True, verbose_name='Текст (если без файла)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оферта',
                'verbose_name_plural': 'Оферта',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Политика конфиденциальности', max_length=160, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='privacy', max_length=64, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политики конфиденциальности',
            },
        ),
    ]
