# Generated by Django 5.2.7 on 2025-10-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_offerpage_privacypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
